name: Pytest

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: |
          uv sync --dev

      - name: Run unittests with pytest
        run: |
          uv run pytest